
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "BankServiceService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:9191/?wsdl")
public class BankServiceService
    extends Service
{

    private final static URL BANKSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException BANKSERVICESERVICE_EXCEPTION;
    private final static QName BANKSERVICESERVICE_QNAME = new QName("http://ws/", "BankServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9191/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANKSERVICESERVICE_WSDL_LOCATION = url;
        BANKSERVICESERVICE_EXCEPTION = e;
    }

    public BankServiceService() {
        super(__getWsdlLocation(), BANKSERVICESERVICE_QNAME);
    }

    public BankServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKSERVICESERVICE_QNAME, features);
    }

    public BankServiceService(URL wsdlLocation) {
        super(wsdlLocation, BANKSERVICESERVICE_QNAME);
    }

    public BankServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKSERVICESERVICE_QNAME, features);
    }

    public BankServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankWS
     */
    @WebEndpoint(name = "BankWSPort")
    public BankWS getBankWSPort() {
        return super.getPort(new QName("http://ws/", "BankWSPort"), BankWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankWS
     */
    @WebEndpoint(name = "BankWSPort")
    public BankWS getBankWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "BankWSPort"), BankWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKSERVICESERVICE_EXCEPTION!= null) {
            throw BANKSERVICESERVICE_EXCEPTION;
        }
        return BANKSERVICESERVICE_WSDL_LOCATION;
    }

}
